name: Main

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build - Python ${{ matrix.python-version }} on ${{ matrix.operating-system }}:${{ matrix.architecture }}

        strategy:
            matrix:
                operating-system: [ubuntu-latest, macOS-latest]
                python-version: [3.10.2]
                architecture: ["x64"]

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            # Setup to flake8
            # - name: Run pylint
            #   run: |
            #       pylint src/main/pycli/ --output-format=text
            - name: Run pytest
              run: |
                  pytest
